config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'home#index'

  scope 'alerting' do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get 'stats', to: 'dashboard#stats', as: 'dashboard_stats'
    get 'timeline', to: 'dashboard#timeline', as: 'dashboard_timeline'
    get 'jumbotron', to: 'dashboard#jumbotron', as: 'dashboard_jumbotron'

    resources :jobs, only: [:index, :show]

    resources :permanents, path: 'manage' do
      collection do
        get 'tips/:show', to: 'alerts#tips', as: 'tips'
        get ':id/disable', to: 'permanents#disable', as: 'disable'
        get ':id/enable', to: 'permanents#enable', as: 'enable'
      end
    end

    resources :schedules, except: [:show] do
      collection do
        put ':id/trigger', to: 'schedules#trigger', as: 'trigger'
      end
    end
    resources :temporaries, only: %i[index create], path: 'debugger'
    resources :searches, except: [:show]
  end

  scope 'administration' do
    resources :settings, only: [:index, :update]
    resources :tasks, only: [:index, :update, :show]
    resources :accounts, except: [:new, :create, :edit] do
      collection do
        get 'pending', to: 'accounts#pending'
      end
    end

    resources :elastic_endpoints, path: 'elastic/clusters'

    namespace :integration, path: 'integrations' do
      resources :slacks, path: 'slack'
      resources :trellos, path: 'trello'
      resources :emails, path: 'email'
    end
  end
  

  devise_for :users,
             skip: %i[database_authenticatable],
             path: 'u',
             path_names: {
               sign_in: 'user',
               sign_out: 'goodbye',
               sign_up: 'request'
             },
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations',
               two_factor_authentication: 'users/two_factor_authentication'
             }

  devise_scope :user do
    get 'u/otp/:email', to: 'users/registrations#otp_setup', as: 'otp_registration'
  end

end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  skip_after_action :verify_policy_scoped, only: [:index]
  skip_after_action :verify_authorized, only: %i[stats jumbotron]
  before_action :set_stats

  def index
    breadcrumb 'Overview & Status', dashboard_path, match: :exact
    job_timeline
  end

  def stats
    get_dashboard_stats

    respond_to do |format|
      format.js
    end
  end

  def jumbotron
    completed_jobs = Job.where(status: :completed).joins(:alert).where(alerts: {type: 'Permanent'}).group_by_hour(:created_at, last: 24, series: true, current: true)
    jumbo = [
      {
        name: 'Events Returned',
        data: completed_jobs.sum(:raw_event_count),
        color: 'rgb(227,231,237,0.3)',
        dataset: {borderColor: 'rgb(227,231,237,1.0)', spanGaps: true}
      },
      {
        name: 'Alertable Results',
        data: completed_jobs.sum(:actionable_event_count),
        color: '#00cccc',
        dataset: {spanGaps: true}
      }
    ]
    render json: jumbo.chart_json
  end

  def get_dashboard_stats
    job_latency
    guard_stats
    all_events_stats
    failed_job_stats
  end

  private

  def guard_stats
    guards = Guard.where(updated_at: 1.days.ago..@current_time)
    previous_guards = Guard.where(updated_at: 2.days.ago..1.days.ago)
    @stats[:events][:guards][:current] = guards.count
    @stats[:events][:guards][:duplicates_prevented] = Guard.all.sum(:hits) - Guard.all.count
    @stats[:events][:guards][:previous] = previous_guards.count

    @stats[:charts][:guards] = Guard.all.group_by_period(
      :hour,
      :created_at,
      format: '%s',
      last: 24,
    ).count.each_with_index.map do |(_k, v), i|
      [
        i, v
      ]
    end
  end

  def failed_job_stats
    @stats[:jobs][:failed][:current] = Job.where(updated_at: 7.days.ago..@current_time).where(status: :failed).count
    @stats[:jobs][:failed][:previous] = Job.where(updated_at: 14.days.ago..7.days.ago).where(status: :failed).count
  end

  def all_events_stats
    @stats[:events][:all_searched][:current] = Job.where(created_at: 1.days.ago..@current_time).where(
      status: :completed
    ).joins(:alert).where(alerts: {type: 'Permanent'}).sum(
      :raw_event_count
    ).to_i
    @stats[:events][:all_searched][:previous] = Job.where(created_at: 2.days.ago..1.days.ago).where(
      status: :completed
    ).joins(:alert).where(alerts: {type: 'Permanent'}).sum(
      :raw_event_count
    ).to_i
    @stats[:charts][:all_events] = Job.all.group_by_period(
      :hour,
      :created_at,
      format: '%s',
      last: 24
    ).joins(:alert).where(alerts: {type: 'Permanent'}).sum(:raw_event_count).each_with_index.map do |(_k, v), i|
      [
        i, v
      ]
    end
  end

  def actionable_events
    Job.where(created_at: 1.days.ago..@current_time).joins(:alert).where(alerts: {type: 'Permanent'}).sum(:actionable_event_count)
  end

  def job_latency
    job_times = Job.where(created_at: 1.days.ago..@current_time)&.map { |j| j.updated_at - j.created_at }
    previous_job_times = Job.where(created_at: 2.days.ago..1.days.ago)&.map { |j| j.updated_at - j.created_at }
    @stats[:jobs][:latency][:current] = (job_times&.sum / job_times&.size&.to_f).round(2)
    @stats[:jobs][:latency][:previous] = (previous_job_times&.sum / previous_job_times&.size&.to_f).round(2)
    @stats[:charts][:job_latency] = job_times&.each_with_index&.map { |v, i| [i, v] }
  end

  def job_timeline
    @job_timeline = Job.where(created_at: 1.days.ago..@current_time).where.not(actionable_event_count: 0).joins(:alert).where(alerts: {type: 'Permanent'}).limit(10).order(created_at: :desc)
  end

  def set_stats
    @stats = Hash.new { |hash, key| hash[key] = Hash.new(&hash.default_proc) }
    @current_time = Time.current

    @stats[:events][:actionable_event_count] = actionable_events
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
  def human_readable_num(num)
    number_to_human(
      num,
      #number_with_delimiter(num, delimiter: ','),
      precision: 3,
      format: '%n%u',
      units: {
        thousand: 'K',
        million: 'M',
        billion: 'B',
        trillion: 'T'
      }
    )
  end

  def calc_max_for_flot_array(data)
    max_val = 0
    data&.each do |d|
      max_val = d.last if d.last > max_val
    end
    max_val.zero? ? 100 : max_val
  end

  def calc_min_for_flot_array(data)
    min_val = 0
    data&.each do |d|
      min_val = d.last if d.last < min_val
    end
    min_val.zero? ? -100 : min_val
  end

  def calc_pct_arrow(event, invert = false)
    previous = event[:previous]
    current = event[:current]
    
    return nil if previous.nil? || previous.zero?
    
    pct = {
      value: ((current / previous.to_f) * 100.0).round(2),
      arrow: current > previous ? 'up' : 'down'
    }
    pct[:color] = if invert
                    current > previous ? 'danger' : 'success'
                  else
                    current > previous ? 'success' : 'danger'
                  end

    return pct
  end
end

app/views/dashboard/_jumbotron.html.slim
#dashboard-chart.flot-chart

javascript:
  var dashboardAllEvents = "#{@stats[:charts][:lifetime_events]}"
  var dashboardActionableEvents = "#{@stats[:charts][:actionable_events]}"
  var plot = $.plot('#dashboard-chart', [
    {
      data: JSON.parse(dashboardAllEvents),
      color: '#e3e7ed',
      lines: {
        show: true,
        lineWidth: 1.5,
        fill: true,
        fillColor: { colors: [ { opacity: 0.5}, { opacity: .75 } ] }
      }
    }, 
    {
      data: JSON.parse(dashboardActionableEvents),
      color: '#00cccc',
      bars: {
        show: true,
        barWidth: 0.5,
        lineWidth: 0.5,
        fill: true,
        align: "center",
        hoverable: true,
        clickable: true
      }
    }], 
    {
      series: {
        shadowSize: 0
      },
      grid: {
        aboveData: true,
        color: '#e5e9f2',
        borderWidth: 0,
        labelMargin: 0
      },
        yaxis: {
          show: false,
          //showTickLabels: "all",
          //min: 0,
          max: Number("#{calc_max_for_flot_array(@stats[:charts][:lifetime_events])}")*1.5,
          transform: function(v) {return Math.log(v+15); /*move away from zero*/},
          //tickDecimals: 3
          //ticks: 10,
          //minTickSize: 10,
          //tickSize: 10
        },
        xaxis: {
          //mode: "time", 
          //timeformat: "%m/%d/%Y",
          //timezone: 'browser',
          //timeBase: "milliseconds",
          //type: 'logarithmic',
          show: false,
          color: 'rgba(255,255,255,.2)',
          //showTickLabels: "major",
          tickColor: 'rgba(0,0,0,0.04)'
        }
      });

app/views/dashboard/_stats.html.slim
.row.row-sm
  .col-sm-6.col-lg-3
    .card.card-body
      h6.tx-uppercase.tx-12.tx-spacing-1.tx-color-02.tx-semibold.mg-b-8
        | Failed Jobs
        ul.list-inline.d-flex.mg-t-20.mg-sm-t-10.mg-md-t-0.mg-b-0
          li.list-inline-item.d-flex.align-items-center
            span.tx-sans.tx-uppercase.tx-9.tx-medium.tx-color-03
              | Last 7 Days
      .d-flex.d-lg-block.d-xl-flex.align-items-end
        h3.tx-normal.tx-rubik.mg-b-0.mg-r-5.lh-1
          = human_readable_num(@stats[:jobs][:failed][:current])
        p.tx-12.tx-color-03.mg-b-0
          /- pct = calc_pct_arrow(@stats[:jobs][:failed], true)
          /- unless pct.nil? || pct[:value].nan?
            span.tx-medium[class="tx-#{pct[:color]}"]
              = pct[:value]
              | % 
              i.icon[class="ion-md-arrow-#{pct[:arrow]}"]
      .ht-30.text-muted.pd-t-15.tx-sans.tx-uppercase.tx-9.tx-spacing-1.tx-semibold
        a[href="#"]
          | View Job History
        
  .col-sm-6.col-lg-3.mg-t-10.mg-sm-t-0
    .card.card-body
      h6.tx-uppercase.tx-12.tx-spacing-1.tx-color-02.tx-semibold.mg-b-8
        | Duplicates Prevented
        ul.list-inline.d-flex.mg-t-20.mg-sm-t-10.mg-md-t-0.mg-b-0
          li.list-inline-item.d-flex.align-items-center
            span.tx-sans.tx-uppercase.tx-9.tx-medium.tx-color-03
              | All-Time
      .d-flex.d-lg-block.d-xl-flex.align-items-end
        h3.tx-normal.tx-rubik.mg-b-0.mg-r-5.lh-1
          = human_readable_num(@stats[:events][:guards][:duplicates_prevented])
        p.tx-12.tx-color-03.mg-b-0
          /- pct = calc_pct_arrow(@stats[:events][:guards])
          /- unless pct.nil? || pct[:value].nan?
            span.tx-medium[class="tx-#{pct[:color]}"]
              = pct[:value]
              | % 
              i.icon[class="ion-md-arrow-#{pct[:arrow]}"]
      #flot-duplicates-supressed.flot-chart.ht-30
  .col-sm-6.col-lg-3.mg-t-10.mg-lg-t-0
    .card.card-body
      h6.tx-uppercase.tx-12.tx-spacing-1.tx-color-02.tx-semibold.mg-b-8
        | Search Latency
        ul.list-inline.d-flex.mg-t-20.mg-sm-t-10.mg-md-t-0.mg-b-0
          li.list-inline-item.d-flex.align-items-center
            span.tx-sans.tx-uppercase.tx-9.tx-medium.tx-color-03
              | Last 24 Hours
      .d-flex.d-lg-block.d-xl-flex.align-items-end
        - if @stats[:jobs][:latency][:current].nan?
          h3.tx-normal.tx-rubik.mg-b-0.lh-1
            | -
        - else
          h3.tx-normal.tx-rubik.mg-b-0.lh-1
            = @stats[:jobs][:latency][:current]
          h4.tx-normal.tx-rubik.mg-b-0.mg-r-5.lh-2
            | sec
        p.tx-12.tx-color-03.mg-b-0
          /- pct = calc_pct_arrow(@stats[:jobs][:latency], true)
          /- unless pct.nil? || pct[:value].nan?
            span.tx-medium[class="tx-#{pct[:color]}"]
              = pct[:value]
              | % 
              /i.icon[class="ion-md-arrow-#{pct[:arrow]}"]
      #flot-job-latency.flot-chart.ht-30
  .col-sm-6.col-lg-3.mg-t-10.mg-lg-t-0
    .card.card-body
      h6.tx-uppercase.tx-12.tx-spacing-1.tx-color-02.tx-semibold.mg-b-8
        | Events Processed
        ul.list-inline.d-flex.mg-t-20.mg-sm-t-10.mg-md-t-0.mg-b-0
          li.list-inline-item.d-flex.align-items-center
            span.tx-sans.tx-uppercase.tx-9.tx-medium.tx-color-03
              | Last 24 Hours
      .d-flex.d-lg-block.d-xl-flex.align-items-end
        h3.tx-normal.tx-rubik.mg-b-0.mg-r-5.lh-1
          = human_readable_num(@stats[:events][:all_searched][:current])
        p.tx-12.tx-color-03.mg-b-0
          /- pct = calc_pct_arrow(@stats[:events][:all_searched])
          /- unless pct.nil?
            span.tx-medium
              = pct[:value]
              | % 
              i.icon[class="ion-md-arrow-#{pct[:arrow]}"]
        
      #flot-lifetime-documents.flot-chart.ht-30

javascript:
  var lifetimeDocuments = "#{@stats[:charts][:all_events]}";
  var jobLatency = "#{@stats[:charts][:job_latency]}";
  var duplicatesSupressed = "#{@stats[:charts][:guards]}";

  function plotStats(selector, dataArray) {
    $.plot(selector, [{
        data: JSON.parse(dataArray),
        color: '#9db2c6'
      }], {
      series: {
        shadowSize: 0,
        lines: {
          show: true,
          lineWidth: 2,
          fill: true,
          fillColor: { colors: [ { opacity: 0 }, { opacity: .5 } ] }
        }
      },
      grid: {
        borderWidth: 0,
        labelMargin: 0
      },
      yaxis: {
        show: false,
        min: 0,
        max: Number("#{calc_max_for_flot_array(@stats[:charts][:all_events])}")
      },
      xaxis: { show: false }
    });
  }

  plotStats('#flot-lifetime-documents', lifetimeDocuments);
  plotStats('#flot-job-latency', jobLatency);
  plotStats('#flot-duplicates-supressed', duplicatesSupressed);
  //plotStats('#flot-lifetime-documents', lifetimeDocuments);

app/views/dashboard/_timeline.html.slim
.timeline-group.mg-t-15
  - unless job_timeline.count.zero?
    - job_timeline.each do |j|
      .timeline-item
        .timeline-time.tx-12
          = j.created_at.in_time_zone(@user_tz).strftime("%b %d")
          br
          span.text-muted
             = j.created_at.in_time_zone(@user_tz).strftime("%l:%M%P")
        .timeline-body
          h5.mg-b-0
            = j.alert.name
            ul.list-inline.d-flex
              li.list-inline-item.d-flex.align-items-center
                a.badge.mg-t-5.btn-icon.btn-xs.badge-lighter.tx-sans.tx-12.tx-medium.alert-link.popover-badge[href="javascript://" data-title="Raw Query<a class='btn btn-info btn-icon mg-t-0 btn-xs lh-3 float-right clipboard-copy'><i class='clipboard-copy-icon'></i></a>" data-trigger='manual' data-toggle="popover" data-placement="right" data-content="<pre class='copy-target'>#{JSON.neat_generate(JSON.parse(j.raw_query), padding: 2, aligned: true, sort: true, wrap: true )}</pre>"]
                  = "Raw Query"
              
          .row
            .col-sm-6
              h3.tx-normal.tx-rubik.tx-spacing--2.mg-b-5.text-tx-inverse.tx-30
                = j.raw_event_count
              h6.tx-uppercase.tx-12.tx-spacing-1.tx-color-02.tx-semibold.mg-b-10
                = "Total #{'Result'.pluralize(j.raw_event_count)}"
            .col-sm-6
              h3.tx-normal.tx-rubik.tx-spacing--2.mg-b-5.tx-pink.tx-30
                = j.actionable_event_count
              h6.tx-uppercase.tx-12.tx-spacing-1.tx-color-02.tx-semibold.mg-b-10
                = "Alertable #{'Event'.pluralize(j.actionable_event_count)}"
          .timeline-divider-text.mg-b-20
            = "Completed @ #{j.updated_at.strftime("%l:%M%P")}"

    javascript:
      $('[data-toggle="popover"]').popover(
        {
          html: true, 
          template: '<div class="popover popover-header-primary event-debug-popover" role="tooltip"><div class="arrow"></div><h3 class="popover-header"></h3><div class="popover-body"></div></div>',
        });

      $('.popover-badge').on('click', function(e) {
        e.preventDefault();
        $('.popover-badge').popover('hide');
        $(this).popover('toggle');
      });

      //$( document ).ready(function() {
        
      //});

      

      $(document).on('click touchstart', function(e){
        //e.preventDefault();
        if ($('.event-debug-popover.show').length) {
          if($(e.target).closest('.popover-badge').length) { 
            $(e.target).closest('.popover-badge').on('shown.bs.popover', function () {
              $('.clipboard-copy-icon').attr('data-feather', 'clipboard');
              feather.replace();
              $('.clipboard-copy').attr('data-clipboard-text', $(document).find('.copy-target, pre').text());
              new ClipboardJS('.clipboard-copy');
            });
            return 
          }
          if(!$(e.target).closest('.event-debug-popover.show').length) {{
              $('.popover-badge').popover('hide');
            }
          }
        }
      });

      
  - else
    .col-md-12
      .alert.alert-info
        | No recent history to display
    

app/views/dashboard/index.html.slim
- if current_user.admin? && (Task&.all&.count&.zero? || Setting&.all&.count != 1)
  .alert.alert-warning.alert-dismissible.fade.show[role="alert"]
    .alert-heading
      strong
        | Setup Incomplete
      ul.mg-b-0
        - if Task&.all&.count&.zero?
          li
            | The default maintenance jobs do not exist; this may indicate a problem with the database setup. 
            = link_to :tasks do
              | Click here 
            | to finish important setup steps.
        - if Setting&.all&.count != 1
          li
            | The default settings are not set; this may indicate a problem with the database setup.  
            = link_to :settings do
              | Click here 
            | to finish important setup steps.
    button.close[type="button" data-dismiss="alert" aria-label="Close"]
      span[aria-hidden="true"]
        | ×
#dashboard-stats

.row.mg-b-10
.row.row-xs
  .col-sm-7.col-lg-7.col-md-7
    .card
      .card-header.pd-y-20.d-md-flex.align-items-center.justify-content-between
        h6.mg-b-0
          | Alert Statistics
        ul.list-inline.d-flex.mg-t-20.mg-sm-t-10.mg-md-t-0.mg-b-0
          li.list-inline-item.d-flex.align-items-center
            span.d-block.wd-10.ht-10.bg-teal.rounded.mg-r-5
            span.tx-sans.tx-uppercase.tx-12.tx-medium.tx-color-03
              | Alertable Events
          li.list-inline-item.d-flex.align-items-center.mg-l-5
            span.d-block.wd-10.ht-10.bg-gray-200.rounded.mg-r-5
            span.tx-sans.tx-uppercase.tx-12.tx-medium.tx-color-03
              | All Events
      .card-body.pos-relative.pd-0
        .pos-absolute.t-20.l-20.wd-xl-100p.z-index-10
          .row
            .col-sm-5
              h3#jumbotron-alertable-event-count.tx-normal.tx-rubik.tx-spacing--2.mg-b-5.tx-40
                = "#{human_readable_num(@stats[:events][:actionable_event_count])}"
              h6.tx-uppercase.tx-12.tx-spacing-1.tx-color-02.tx-semibold.mg-b-10
                | Alertable Events
            /.col-sm-5.mg-t-20.mg-sm-t-0
              h3.tx-normal.tx-rubik.tx-spacing--2.mg-b-5.tx-40
                = ((@stats[:events][:actionable_event_count] / @stats[:events][:all_searched][:current].to_f)*100).round(3)
                | %
              h6.tx-uppercase.tx-12.tx-spacing-1.tx-color-02.tx-semibold.mg-b-10
                | Of  Are Alerts
        /- unless @stats[:events][:actionable_event_count].zero?
        #dashboard-jumbotron
          = area_chart dashboard_jumbotron_path, refresh: 15, height: '350px', id: 'jumbotron-chart', thousands: ",", library: {\
              responsive: true,\
              maintainAspectRatio: false,\
              legend: {\
                display: false,\
                labels: {\
                  display: false\
                }\
              },\
              hover: {\
                mode: 'index',\
                intersect: true,\
              },\
              tooltips: {\
                mode: 'index',
                intersect: true,\
                position: 'nearest',\
                bodyFontFamily: '-apple-system, BlinkMacSystemFont, "Inter UI", Roboto, sans-serif',\
              },\
              elements: {\
                point: {\
                  radius: 1.8,\
                  hoverRadius: 3,\
                  pointStyle: 'circle',\
                },\
                line: {\
                  tension: 0.25,\
                },\
              },\
              scales: {\
                xAxes: [{\
                  type: 'time',\
                  distribution: 'series',
                  time: {\
                    unit: 'minute',\
                  },\
                  gridLines: {\
                    color: '#e5e9f2',\
                    drawOnChartArea: false,\
                    zeroLineColor: 'rgba(50,58,78,0.0)',\
                    display: false,\
                    zeroLineWidth: 0,\
                    tickMarkLength: 0\
                  },\
                  ticks: {\
                    display: false,\
                    fontColor: '#8392a5',\
                    fontSize: 10,\
                    fontStyle: '500',\
                    fontFamily: '-apple-system, BlinkMacSystemFont, "Inter UI", Roboto, sans-serif',\
                    maxTicksLimit: 5,\
                  }\
                }],\
                yAxes: [{\
                  type: 'logarithmic',\
                  gridLines: {\
                    color: '#ebeef3',\
                    drawBorder:false,\
                    tickMarkLength: 0,\
                    display: false\
                  },\
                  ticks: {\
                    display: false,\
                    fontColor: '#8392a5',\
                    fontSize: 10,\
                    fontStyle: '500',\
                    fontFamily: '-apple-system, BlinkMacSystemFont, "Inter UI", Roboto, sans-serif',\
                    maxTicksLimit: 7,\
                  }\
                }],\
              }\
          }
  .col-sm-5.col-lg-5.col-md-5
    .card
      .card-header.pd-y-20.d-md-flex.align-items-center.justify-content-between
        h6.mg-b-0
          | History
        ul.list-inline.d-flex.mg-t-20.mg-sm-t-10.mg-md-t-0.mg-b-0
          li.list-inline-item.d-flex.align-items-center
            span.d-block.wd-10.ht-10.bg-df-1.rounded.mg-r-5
            span.tx-sans.tx-uppercase.tx-12.tx-medium.tx-color-03
              | Last 10 Jobs With Alerts
      .card-body.pos-relative.pd-0
        #timeline-container
          = render 'timeline', job_timeline: @job_timeline

  = javascript_include_tag 'charts'
  = javascript_include_tag 'dashboard'

  javascript:
    
    $("#timeline-container").slimScroll({height: "465px", size: "3px"});
    getStats("#{dashboard_stats_path(:format => :js )}");

app/views/dashboard/jumbotron.js.slim
| $("#dashboard-jumbotron").html("
= j render 'jumbotron'
| ");
| $("#jumbotron-alertable-event-count").text("#{human_readable_num(@stats[:events][:actionable_event_count])}");

app/views/dashboard/stats.js.slim
| $("#dashboard-stats").html("
= j render 'stats'
| ")