config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'home#index'

  scope 'alerting' do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get 'stats', to: 'dashboard#stats', as: 'dashboard_stats'
    get 'timeline', to: 'dashboard#timeline', as: 'dashboard_timeline'
    get 'jumbotron', to: 'dashboard#jumbotron', as: 'dashboard_jumbotron'

    resources :jobs, only: [:index, :show]

    resources :permanents, path: 'manage' do
      collection do
        get 'tips/:show', to: 'alerts#tips', as: 'tips'
        get ':id/disable', to: 'permanents#disable', as: 'disable'
        get ':id/enable', to: 'permanents#enable', as: 'enable'
      end
    end

    resources :schedules, except: [:show] do
      collection do
        put ':id/trigger', to: 'schedules#trigger', as: 'trigger'
      end
    end
    resources :temporaries, only: %i[index create], path: 'debugger'
    resources :searches, except: [:show]
  end

  scope 'administration' do
    resources :settings, only: [:index, :update]
    resources :tasks, only: [:index, :update, :show]
    resources :accounts, except: [:new, :create, :edit] do
      collection do
        get 'pending', to: 'accounts#pending'
      end
    end

    resources :elastic_endpoints, path: 'elastic/clusters'

    namespace :integration, path: 'integrations' do
      resources :slacks, path: 'slack'
      resources :trellos, path: 'trello'
      resources :emails, path: 'email'
    end
  end
  

  devise_for :users,
             skip: %i[database_authenticatable],
             path: 'u',
             path_names: {
               sign_in: 'user',
               sign_out: 'goodbye',
               sign_up: 'request'
             },
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations',
               two_factor_authentication: 'users/two_factor_authentication'
             }

  devise_scope :user do
    get 'u/otp/:email', to: 'users/registrations#otp_setup', as: 'otp_registration'
  end

end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  validates :cron,
            presence: {
              message: 'Cron expression required.'
            }

  validate :parseable?

  after_save do |t|
    sidekiq_task = Sidekiq::Cron::Job.find(t.uid)
    if sidekiq_task.nil?
      new_task = {
        t.uid => {
          'class' => t.worker.to_s,
          'cron' => t.cron
        }
      }
      Sidekiq::Cron::Job.load_from_hash new_task
    else
      sidekiq_task.cron = t.cron unless sidekiq_task.cron.eql?(t.cron)
      enabled? ? sidekiq_task.enable! : sidekiq_task.disable!
    end
  end

  def last_execution_time
    sidekiq_task = Sidekiq::Cron::Job.find(uid)
    sidekiq_task&.last_enqueue_time
  end

  def worker
    "#{type.split('::').last.singularize}Worker".constantize
  end

  def enqueue
    sidekiq_task = Sidekiq::Cron::Job.find(uid)
    sidekiq_task&.enque!
  end

  def uid
    Digest::SHA1.hexdigest type
  end

  def parseable?
    Fugit.do_parse_cron(cron)
    true
  rescue StandardError => e
    errors.add(:cron, 'Invalid cron format.')
  end
end

app/models/task/failed_job.rb
class Task::FailedJob < ::Task
end

app/models/task/inactive_account.rb
class Task::InactiveAccount < ::Task
end

app/models/task/prune_job_history.rb
class Task::PruneJobHistory < ::Task
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[update show]
  breadcrumb 'Administration', '', match: :exact

  def index
    breadcrumb 'Maintenance Jobs', tasks_path, match: :exact
    
    @tasks = policy_scope(Task.all)
    if @tasks&.count&.zero?
      @tasks = setup_default_tasks 
      flash[:notice] = 'Maintenance jobs installed successfully.'
    end 
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
      else
        format.html { render :index }
      end
    end
  end

  def show
    @task.enqueue
    respond_to do |format|
      format.html { redirect_to tasks_path, notice: 'Task was enqueued.' }
    end
  end

  private

  def set_task
    @task = authorize Task.find(params[:id])
  end

  def task_params
    if params.key?(:task_failed_job)
      params.require(:task_failed_job).permit(:cron, :enabled)
    elsif params.key?(:task_inactive_account)
      params.require(:task_inactive_account).permit(:cron, :enabled)
    end
  end

  def setup_default_tasks
    namespaced_tasks = Task.constants.select {|c| Task.const_get(c).is_a?(Class) && Task.const_get(c).to_s.include?('Policy')}.map { |t| t.to_s.sub('Policy', '')}
    namespaced_tasks.each do |t|
      "Task::#{t}".constantize.create!(cron: Rails.application.config.default_cron, enabled: true)
    end
    policy_scope(Task.all)
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
  def task_last_execution(task)
    if task&.last_execution_time.nil?
      'Never'
    else
      task&.last_execution_time&.in_time_zone(@user_tz)&.strftime('%m/%d/%Y @ %I:%M:%S%p')
    end
  end
end

app/views/tasks/_task_card.html.slim
- unless c.nil?
  .card
    = form_with(model: c, url: task_path(c), method: :put, local: true) do |form|
      .card-body
        h5.card-title.mg-b-5
          = c.type.split('::').last.pluralize.titleize
        p.card-text
          .form-row
            .form-group.col-md-12
              label.d-block
                | Cron Expression: 
                span.tx-danger
                  | *
              = form.text_field :cron, class: 'tx-roboto-mono form-control', autofill: false
              .tx-danger.tx-12
                = inline_errors(c, :cron)
          .form-row
            .form-group.col-md-6
              .custom-control.custom-switch
                = form.check_box :enabled, class: "custom-control-input"
                = form.label(:enabled, "Enabled", class: "custom-control-label")
        small.text-muted.tx-13
            = "Last executed: #{task_last_execution(c)}"
      .card-footer
        = form.submit "Update Job", class: "btn btn-primary btn-sm mg-r-5"
        = link_to task_path(c), class: 'btn btn-light btn-sm' do
          | Run now
    /.card-footer
      .row.row-sm
        .col-md-8
          .btn-toolbar[role="toolbar" aria-label="Toolbar with button groups"]
            .btn-group.mr-2[role="group" aria-label="First group"]
              = link_to edit_permanent_path(c) do
                button.btn.btn-outline-primary.btn-sm[type="button"]
                  | Edit
              button.btn.btn-outline-primary.btn-sm[type="button"]
                | History
              button.btn.btn-outline-primary.btn-sm[type="button"]
                | Disabl

app/views/tasks/index.html.slim
- unless @tasks.nil? || @tasks&.count&.zero?
  - @tasks&.each_slice(3) do |c1, c2, c3|
    .row
      .col-md-4
          = render 'task_card', c: c1
      .col-md-4
          = render 'task_card', c: c2
      .col-md-4
          = render 'task_card', c: c3