config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'home#index'

  scope 'alerting' do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get 'stats', to: 'dashboard#stats', as: 'dashboard_stats'
    get 'timeline', to: 'dashboard#timeline', as: 'dashboard_timeline'
    get 'jumbotron', to: 'dashboard#jumbotron', as: 'dashboard_jumbotron'

    resources :jobs, only: [:index, :show]

    resources :permanents, path: 'manage' do
      collection do
        get 'tips/:show', to: 'alerts#tips', as: 'tips'
        get ':id/disable', to: 'permanents#disable', as: 'disable'
        get ':id/enable', to: 'permanents#enable', as: 'enable'
      end
    end

    resources :schedules, except: [:show] do
      collection do
        put ':id/trigger', to: 'schedules#trigger', as: 'trigger'
      end
    end
    resources :temporaries, only: %i[index create], path: 'debugger'
    resources :searches, except: [:show]
  end

  scope 'administration' do
    resources :settings, only: [:index, :update]
    resources :tasks, only: [:index, :update, :show]
    resources :accounts, except: [:new, :create, :edit] do
      collection do
        get 'pending', to: 'accounts#pending'
      end
    end

    resources :elastic_endpoints, path: 'elastic/clusters'

    namespace :integration, path: 'integrations' do
      resources :slacks, path: 'slack'
      resources :trellos, path: 'trello'
      resources :emails, path: 'email'
    end
  end
  

  devise_for :users,
             skip: %i[database_authenticatable],
             path: 'u',
             path_names: {
               sign_in: 'user',
               sign_out: 'goodbye',
               sign_up: 'request'
             },
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations',
               two_factor_authentication: 'users/two_factor_authentication'
             }

  devise_scope :user do
    get 'u/otp/:email', to: 'users/registrations#otp_setup', as: 'otp_registration'
  end

end

app/models/schedule.rb
# frozen_string_literal: true

class Schedule < ApplicationRecord
  belongs_to :alert
  belongs_to :user

  has_many :jobs, dependent: :destroy

  enum period: %i[minutes hours days weeks months]

  after_save do |s|
    sidekiq_task = s.job
    if sidekiq_task.nil?
      create_job
    else
      sidekiq_task.cron = s.cron unless sidekiq_task.cron.eql?(s.cron)
      enabled? ? sidekiq_task.enable! : sidekiq_task.disable!
    end
  end

  after_destroy do
    destroy_job
  end

  def next
    Fugit::Cron.parse(cron).next_time
  end

  def last
    Fugit::Cron.parse(cron).previous_time
  end

  def schedule_uid
    Digest::SHA1.hexdigest alert&.name
  end

  def destroy_job
    job&.destroy
  end

  def run_job
    create_job if job.nil?
    job&.enque!
  end

  def create_job
    new_task = {
      schedule_uid => {
        'class' => 'ScheduleWorker',
        'cron' => cron,
        'args' => id
      }
    }
    Sidekiq::Cron::Job.load_from_hash new_task
  end

  def range_in_seconds
    Fugit.parse("#{range} #{period}").to_sec
  end

  def job
    Sidekiq::Cron::Job.find(schedule_uid)
  end

  validates :cron,
            presence: {
              message: 'Cron expression required.'
            }

  validate :parseable?

  validates :range,
            presence: {
              message: 'Range must be specified'
            }, numericality: {
              only_integer: true,
              greater_than: 0,
              message: 'Range must be an integer'
            },uniqueness: {
              scope: :alert_id,
              message: 'Schedule already exists with the current cron frequency',
              case_sensitive: false
            }

  validates :period,
            inclusion: {
              in: %w[minutes hours days weeks months],
              message: 'Invalid period.'
            }
            
  def parseable?
    begin
      Fugit.do_parse_cron(cron)
      true
    rescue => e
      errors.add(:cron, 'Invalid cron format.')
    end
  end
end

app/controllers/schedules_controller.rb
# frozen_string_literal: true

class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[show edit update destroy trigger]

  breadcrumb 'Scheduling', '', match: :exact

  # GET /schedules
  # GET /schedules.json
  def index
    breadcrumb 'Schedule Management', schedules_path, match: :exact
    @schedules = policy_scope(Schedule.all)

    # if Alert.all.count.zero?
    #   flash[:alert] = 'No alerts defined. Create one first.'
    #   redirect_to new_permanent_path
    #   return
    # end
    # redirect_to new_schedule_path, notice: 'No schedules to show yet; create one here.' if @schedules.empty?
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show; end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
    breadcrumb 'New Schedule', new_schedule_path, match: :exact

    if policy_scope(Alert.all).count.zero?
      flash[:alert] = 'No alerts defined. Create one first.'
      redirect_to new_permanent_path
      return
    end
  end

  # GET /schedules/1/edit
  def edit; end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.user = current_user

    authorize @schedule

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedules_path, notice: 'Schedule was successfully created.' }
        # format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        # format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to schedules_path, notice: "Schedule for #{@schedule.alert.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def trigger
    @schedule.run_job
    head :ok
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: "Schedule for #{@schedule.alert.name} was deleted successfully." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_schedule
    @schedule = authorize Schedule.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def schedule_params
    params.require(:schedule).permit(:cron, :period, :range, :alert_id, :enabled)
  end
end

app/views/schedules/_form.html.slim
= form_with(model: schedule, local: true) do |form|
  .form-row
    .form-group.col-md-5
      label.d-block
        | Alert: 
        span.tx-danger
          | *
      = form.select(:alert_id, Permanent.all.map {|p| [p.name,p.id]}, {}, { :class => "custom-select" })
      .tx-danger.tx-12
        = inline_errors(schedule, :alert_id)
    .form-group.col-md-3
      label.d-block
        | Cron Expression: 
        span.tx-danger
          | *
      = form.text_field :cron, class: 'tx-roboto-mono form-control', autofill: false
      .tx-danger.tx-12
        = inline_errors(schedule, :cron)
    .form-group.col-md-4
      label.d-block
        | Time Range: 
        span.tx-danger
          | *
      .input-group
        .input-group-prepend
          span.input-group-text
            | Last
        = form.text_field :range, class: 'form-control', autofill: false
        = form.select(:period, Schedule.periods.keys.map {|p| [p,p]}, {}, { :class => "custom-select" })
      .tx-danger.tx-12
        = inline_errors(schedule, :range)

  .divider-text.mg-b-20
    a#schedule-generator-expand[data-toggle="collapse" href="#cronCollapse" role="button" aria-expanded="false" aria-controls="cronCollapse"]
      | Show Cron Generator 
      i[data-feather="clock"]
  #cronCollapse.collapse.mg-t-5
    .form-group.alert.bg-gray-100
      label.d-block.tx-dark
        | Executes: 
      #schedule-generator.tx-light.tx-13
  /.form-group
    label.d-block
      | Time Range: 
    = form.text_field :range
    .tx-danger.tx-12
      = inline_errors(schedule, :range)
     
  = form.submit "Save schedule", class: "btn btn-primary"

= javascript_include_tag 'schedule'

app/views/schedules/edit.html.slim
.row
  .col-md-10
    = render 'shared/errors', c: @schedule
    = render 'form', schedule: @schedule

app/views/schedules/index.html.slim
.row.mg-b-15
  .col-sm-12
    .d-flex.justify-content-end
      = link_to :new_schedule do
        button.btn.btn-primary[type="button"]
          i[data-feather="plus"]
          |  New Schedule
.row
  .col-sm-12
    .table-responsive-sm
      table.table#schedule-table
        thead
          tr
            th[scope="col" class="no-sort enabled-column"]
              | Enable?
            th[scope="col"]
              | Alert
            th[scope="col"]
              | Cron 
            th[scope="col"]
              | Range
            th[scope="col"]
              | Last Run
            th[scope="col"]
              | Next Run
            th[scope="col" class="no-sort action-column"]
        tbody
          - @schedules.each do |schedule|
            tr
              td
                = form_for(schedule, remote: true) do |form|
                  .custom-control.custom-switch.pd-l-20
                    = form.check_box :enabled, {class: "custom-control-input", id: "schedule_#{schedule.id}_enabled"}, "true", "false"
                    = form.label :enabled, "&#8203;".html_safe, class: 'custom-control-label mg-l-25', id: "schedule_label_#{schedule.id}_enabled", for: "schedule_#{schedule.id}_enabled"
                    /label.custom-control-label[for="schedule_enabled"]
              td
                = schedule.alert.name
              td.tx-roboto-mono.tx-pink
                = schedule.cron
              td
                = "#{pluralize(schedule.range, schedule.period)}"
              td
                - last_job = schedule&.jobs&.last
                - unless last_job.nil?
                  = schedule.last.in_time_zone(@user_tz).strftime("%m/%d/%Y @ %I:%M:%S%p")
                - else
                  | Never
              td
                - if schedule&.enabled?
                  = schedule.next.in_time_zone(@user_tz).strftime("%m/%d/%Y @ %I:%M:%S%p")
                - else
                  | -

              td
                .dropdown.dropright
                  button#droprightMenuButton.btn.btn-icon.btn-secondary.btn-xs.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
                    i[data-feather="settings"]
                  .dropdown-menu[aria-labelledby="droprightMenuButton"]
                    /= link_to schedule_path(schedule), :class => "dropdown-item" do
                    = link_to trigger_schedules_path(schedule), data: {\
                      title: "Force Run #{schedule.alert.name}?",\
                      confirm: '<h5 class="tx-dark">Any actions will be triggered just as if this was a scheduled run.</h5><p>Are you sure?</p>',\
                      commit: 'Yes, run this schedule.', 'cancel-class': 'btn-secondary', 'commit-class': 'btn-success'},\
                      :class => "dropdown-item", :method => :put, remote: true do
                        | Execute now
                    = link_to permanent_path(schedule.alert), class: "dropdown-item" do
                      | History
                    = link_to edit_schedule_path(schedule), :class => "dropdown-item" do
                      | Edit
                    .dropdown-divider 
                    = link_to schedule_path(schedule), data: {\
                      title: "Delete Schedule?",\
                      confirm: "<h5 class='tx-danger'><p>Confirm deletion for schedule: #{schedule.alert.name} (#{schedule.cron})</p></h5><p>This action cannot be undone.</p>",\
                      commit: 'Yes, delete this schedule.', 'cancel-class': 'btn-secondary'},\
                      :class => "dropdown-item", :method => :delete do
                        | Delete
    = javascript_include_tag 'datatable'
    
    javascript:

      $('#schedule-table').DataTable({
        language: {
          searchPlaceholder: 'Search...',
          sSearch: '',
          lengthMenu: '_MENU_ items/page'
        },
        order: [[ 1, "desc" ]],
        columnDefs: [{ targets: 'no-sort', orderable: false }, { targets: 'action-column', width: "28px"}, { targets: 'enabled-column', width: "50px"}]
      });
      $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });

      $("[id^=schedule_], input[type=checkbox]").on('change', function(e) {
        var scheduleForm = $(this).closest('form');
        scheduleForm.submit();
      });

app/views/schedules/new.html.slim
.row
  .col-md-10
    = render 'shared/errors', c: @schedule
    = render 'form', schedule: @schedule