config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  root to: 'home#index'

  scope 'alerting' do
    get '/', to: 'dashboard#index', as: 'dashboard'
    get 'stats', to: 'dashboard#stats', as: 'dashboard_stats'
    get 'timeline', to: 'dashboard#timeline', as: 'dashboard_timeline'
    get 'jumbotron', to: 'dashboard#jumbotron', as: 'dashboard_jumbotron'

    resources :jobs, only: [:index, :show]

    resources :permanents, path: 'manage' do
      collection do
        get 'tips/:show', to: 'alerts#tips', as: 'tips'
        get ':id/disable', to: 'permanents#disable', as: 'disable'
        get ':id/enable', to: 'permanents#enable', as: 'enable'
      end
    end

    resources :schedules, except: [:show] do
      collection do
        put ':id/trigger', to: 'schedules#trigger', as: 'trigger'
      end
    end
    resources :temporaries, only: %i[index create], path: 'debugger'
    resources :searches, except: [:show]
  end

  scope 'administration' do
    resources :settings, only: [:index, :update]
    resources :tasks, only: [:index, :update, :show]
    resources :accounts, except: [:new, :create, :edit] do
      collection do
        get 'pending', to: 'accounts#pending'
      end
    end

    resources :elastic_endpoints, path: 'elastic/clusters'

    namespace :integration, path: 'integrations' do
      resources :slacks, path: 'slack'
      resources :trellos, path: 'trello'
      resources :emails, path: 'email'
    end
  end
  

  devise_for :users,
             skip: %i[database_authenticatable],
             path: 'u',
             path_names: {
               sign_in: 'user',
               sign_out: 'goodbye',
               sign_up: 'request'
             },
             controllers: {
               omniauth_callbacks: 'users/omniauth_callbacks',
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations',
               two_factor_authentication: 'users/two_factor_authentication'
             }

  devise_scope :user do
    get 'u/otp/:email', to: 'users/registrations#otp_setup', as: 'otp_registration'
  end

end

app/models/search.rb
# frozen_string_literal: true

class Search < ApplicationRecord
  attr_encrypted :query,
                 key: Rails.application.credentials.attr_encrypted,
                 encode: true,
                 encode_iv: true,
                 encode_salt: true

  attr_encrypted :indices,
                 key: Rails.application.credentials.attr_encrypted,
                 marshal: true,
                 allow_empty_value: true,
                 encode: true,
                 encode_iv: true,
                 encode_salt: true

  has_many :alerts, dependent: :destroy

  belongs_to :user
  belongs_to :elastic_endpoint


  before_validation do |s|
    s.indices = s.indices.gsub(/ /, '') unless s.indices.blank?
  end

  validates_associated :elastic_endpoint

  validates :name,
            uniqueness: {
              message: 'A search already exists with that name. Please choose another.',
              case_sensitive: false
            },
            presence: {
              message: 'Please specify a name for this search.'
            },
            format: {
              with: /\A[A-Za-z0-9 ]+\z/,
              message: 'Search names may only contain alphanumeric and space characters.'
            }

  validates :indices,
            presence: {
              message: 'A search requires at least one index.'
            }

  validates :query,
            presence: {
              message: 'Enter a query'
            }

  def index_array
    indexes = []
    indices.split(',').each do |i|
      indexes.push(i)
    end
    indexes
  end
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  before_action :set_search, only: %i[show edit results update destroy]
  before_action :set_elastic_endpoints, only: %i[index new]

  breadcrumb 'Elasticsearch', '', match: :exact

  # GET /searches
  # GET /searches.json
  def index
    breadcrumb 'Saved Searches', searches_path, match: :exact
    @searches = policy_scope(Search.all)
  end

  # GET /searches/new
  def new
    breadcrumb 'Saved Searches', searches_path, match: :exact
    breadcrumb 'Create Search', new_search_path, match: :exact
    unless policy_scope(ElasticEndpoint.all).empty?
      @search = Search.new
    end
  end

  # GET /searches/1/edit
  def edit
    breadcrumb 'Saved Searches', searches_path, match: :exact
    breadcrumb 'Edit Search', edit_search_path(@search), match: :exact
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)
    
    @search.permanent = true
    @search.user = current_user

    authorize @search

    respond_to do |format|
      if @search.save
        format.html { redirect_to searches_path, notice: 'Search was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to searches_path, notice: "#{@search.name} was successfully updated." } 
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: "#{@search.name} was deleted successfully." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_search
    @search = authorize Search.find(params[:id])
  end

  def set_elastic_endpoints
    @elastic_endpoints = policy_scope(ElasticEndpoint.all)
  end

  def search_params
    params.require(:search).permit(:name, :query, :indices, :elastic_endpoint_id)
  end
end

app/views/searches/_form.html.slim
= javascript_include_tag 'form-tags'

= form_with(model: search, local: true) do |form|
  .form-row
    .form-group.col-md-6
      label.d-block
        | Name: 
        span.tx-danger
          | *
      = form.text_field :name, class: "form-control", placeholder: "Something to remember the search by", autocomplete: "off"
      .tx-danger.tx-12
        = inline_errors(search, :name)
    .form-group.col-md-6
      label.d-block
        | Elasticsearch Cluster: 
        span.tx-danger
          | *
      = form.select(:elastic_endpoint_id, ElasticEndpoint.all.map {|p| [p.name,p.id]}, {}, { :class => "custom-select" })
      .tx-danger.tx-12
        = inline_errors(search, :elastic_endpoint_id)
  .form-group
    label.d-block
      | Index Pattern(s): 
      span.tx-danger
        | *
    = form.text_field :indices, class: "form-control", autocomplete: "off", :data => { role: "tagsinput", toggle: "tooltip" }
    .tx-danger.tx-12
      = inline_errors(search, :indices)
  .form-group
    label.d-block
      | Search Query: 
      span.tx-danger
        | *
    = form.text_field :query, class: "tx-roboto-mono form-control", placeholder: "eg: user:john.doe AND _exists_:email"
    .tx-danger.tx-12
      = inline_errors(search, :query)
  hr
  = form.submit "Save search", class: "btn btn-primary"

/= javascript_include_tag 'search'

javascript:
 
  var tagTextbox = $('#search_indices').tagsinput({
    confirmKeys: [13, 44, 32],
    trimValue: true
  });

  if(tagTextbox && tagTextbox[0] !== undefined && tagTextbox[0] != false) {
    var tooltipTarget = tagTextbox[0].$container;
    if(tooltipTarget && tooltipTarget !== undefined && tooltipTarget != false) {
      var realTextbox = tagTextbox[0].$input
      realTextbox.attr("autocomplete", "off");
      tooltipTarget.attr("data-placement", "left");
      realTextbox.attr("data-lpignore", "true");
      tooltipTarget.attr("title", "Can be a single index, an index pattern (eg: logstash-*), or a combination of the two.");
      tooltipTarget.tooltip();
    } 
  }

app/views/searches/edit.html.slim
.row
  .col-sm-9
    = render 'shared/errors', c: @search
    .card
      .card-body
        = render 'form', search: @search
              

app/views/searches/index.html.slim
- if @elastic_endpoints&.count&.zero?
  .row
    .col-sm-8
      .card
        .card-body
          h5.card-title
            | Elasticsearch cluster not found!
          p.card-text
            | You'll need to configure at least one Elasticsearch cluster before you can create a search.
        .card-footer 
          = link_to :new_elastic_endpoint do
            button.btn.btn-primary[type="button"]
              i[data-feather="plus"]
              |  New cluster
- else
  .row.mg-b-15
    .col-sm-12
      .d-flex.justify-content-end
        = link_to :new_search do
          button.btn.btn-primary[type="button"]
            i[data-feather="plus"]
            |  New Search
  .row
    .col-sm-12
      .table-responsive-sm
        table.table.table-hover#search-table
          thead
            tr
              th[scope="col"]
                | Name
              th[scope="col"]
                | Query
              th[scope="col"]
                | Cluster
              th[scope="col" class="no-sort action-column"]
          tbody
            - @searches&.each do |search|
              tr
                td
                  = search.name
                td
                  span.tx-roboto-mono.tx-13.tx-pink
                    = truncate(search.query, length: 55, separator: ' ', omission: '... ') {\
                    link_to "(see full query)", "#", class: "tooltip-wide", title: "#{search.query}", data: { template: "<div class='tooltip' role='tooltip'><div class='arrow'></div><div class='tooltip-inner tooltip-search-query'></div></div>", toggle: "tooltip", placement: "bottom" }\
                    }
                td
                  = link_to elastic_endpoint_path(search.elastic_endpoint), class: 'tx-inverse' do
                    = truncate(search.elastic_endpoint.name, length: 35, separator: ' ', omission: '... ') {\
                      link_to "(see full name)", "#", class: "tooltip-wide", title: search.elastic_endpoint.name, data: { template: "<div class='tooltip' role='tooltip'><div class='arrow'></div><div class='tooltip-inner tooltip-search-query'></div></div>", toggle: "tooltip", placement: "bottom" }\
                    }

                td
                  .dropdown.dropright
                    button#droprightMenuButton.btn.btn-icon.btn-secondary.btn-xs.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"]
                      i[data-feather="settings"]
                    .dropdown-menu[aria-labelledby="droprightMenuButton"]
                      = link_to edit_search_path(search), :class => "dropdown-item" do
                        | Edit
                      .dropdown-divider 
                      = link_to search_path(search), data: {\
                        title: "Delete #{search.name}?",\
                        verify: "#{search.name}",\
                        verify_text: "Type '#{search.name}' to confirm",\
                        confirm: '<h5 class="tx-danger">All alerts and schedules linked to this search will also be deleted. This effectively will remove ALL linked items and may have unintended consequences.</h5>',\
                        commit: 'Yes, delete this search.', 'cancel-class': 'btn-secondary'},\
                        class: "dropdown-item",\
                        method: :delete do
                          | Delete
      = javascript_include_tag 'datatable'
      
      javascript:

        $('#search-table').DataTable({
          language: {
            searchPlaceholder: 'Search...',
            sSearch: '',
            lengthMenu: '_MENU_ items/page',
          },
        columnDefs: [{ targets: 'no-sort', orderable: false }, { targets: 'action-column', width: "28px"}]
        });
        $('.dataTables_length select').select2({ minimumResultsForSearch: Infinity });


        $('[data-toggle="popover"]').popover({
          html: true,
          template: '<div class="popover popover-header-primary event-debug-popover" role="tooltip"><div class="arrow"></div><h3 class="popover-header"></h3><div class="popover-body"></div></div>',
        });

app/views/searches/new.html.slim
- if @elastic_endpoints&.count&.zero?
  .row
    .col-sm-8
      .card
        .card-body
          h5.card-title
            | Hold On A Second
          p.card-text
            | You'll need to configure at least one Elasticsearch cluster before you can create a search.
        .card-footer 
          = link_to :new_elastic_endpoint do
            button.btn.btn-primary[type="button"]
              i[data-feather="plus"]
              |  New Endpoint
- else
  .row
    .col-sm-9
      = render 'shared/errors', c: @search
      .card
        .card-body
          = render 'form', search: @search
              